### ISSUE TITLE
rename repository to Level/mem

### ISSUE THREAD

**Issue by juliangruber** [Level/mem#21]
shall we do this?

**Comment by ralphtheninja** [comment]
Are you looking for symmetry? E.g. `leveldown` is wrapped by `level` so `memdown` should be wrapped by `mem`?

**Comment by juliangruber** [comment]
I was thinking more about consistency, we have `level-packager` at `level/packager` and `level-iterator-stream` at `level/iterator-stream`. There are other repos following the old naming scheme still, but those should be moved over as well in my opinion.

**Comment by ralphtheninja** [comment]
Do it :)
